/**
 * T-132/T-134 — Libellés d'interface localisés (FR par défaut, EN).
 *
 * L'arabe (ar) reste hors périmètre V1 (pas de dictionnaire RTL) : on
 * retombe sur le français. Ce dictionnaire couvre l'interface client
 * (navigation, recherche, fiche, tunnel de réservation, compte, auth…).
 * Utilisable côté serveur (RSC) comme côté client.
 */

export type UiLocale = "fr" | "en";

const FR = {
  // Prix / cartes
  "price.from": "Dès",
  "price.perNight": "/nuit",
  "price.unavailable": "Prix indisponible",
  "price.fromShort": "À partir de",
  "price.perNightLong": "par nuit",
  "price.convertedNote": "Conversion indicative · paiement en",
  // Fiche / carte
  "book.seeAvailability": "Voir les disponibilités",
  "book.noRoom": "Aucune chambre disponible",
  "book.checkIn": "Arrivée",
  "book.checkOut": "Départ",
  "book.adults": "Adultes",
  "book.children": "Enfants",
  "book.cancelShown": "✓ Conditions d'annulation affichées avant confirmation",
  "fav.add": "Ajouter aux favoris",
  "fav.added": "Ajouté aux favoris",
  "card.reviews": "avis",
  "card.viewRooms": "Voir les chambres →",
  // Contact hôte
  "contact.host": "Contacter l'hôte",
  "contact.question": "Poser une question à l'hôte avant de réserver",
  "contact.error": "Impossible de démarrer la conversation",
  "contact.notFound": "Conversation introuvable",
  // Navigation
  "nav.login": "Se connecter",
  "nav.myAccount": "Mon compte",
  "nav.bookings": "Mes réservations",
  "nav.favorites": "Mes favoris",
  "nav.messages": "Messages",
  "nav.dashboard": "Dashboard",
  "nav.logout": "Déconnexion",
  "nav.search": "Recherche",
  "nav.bestrewards": "BestRewards",
  "nav.help": "Aide",
  "nav.accommodations": "Hébergements",
  "nav.signup": "S'inscrire",
  "nav.userMenu": "Menu utilisateur",
  "nav.openMenu": "Ouvrir le menu",
  "nav.closeMenu": "Fermer le menu",
  "footer.discover": "Découvrir",
  "footer.searchAccommodation": "Rechercher un hébergement",
  "footer.helpCenter": "Centre d'aide",
  "footer.travelers": "Voyageurs",
  "footer.messaging": "Messagerie",
  "footer.hosts": "Hébergeurs",
  "footer.addProperty": "Ajouter mon hébergement",
  "footer.hostArea": "Espace hébergeur",
  "footer.createAccount": "Créer un compte",
  "footer.contact": "Contact",
  "footer.tagline": "Réservez mieux. Voyagez plus.",
  "footer.legal": "Mentions légales",
  "footer.privacy": "Confidentialité",
  "footer.rights": "© 2025 MyBestBooking — Tous droits réservés",
  // Recherche (formulaire)
  "search.title": "Recherche d'hébergements",
  "search.destination": "Destination",
  "search.destinationPlaceholder": "Ville ou hébergement",
  "search.arrival": "Arrivée",
  "search.departure": "Départ",
  "search.type": "Type",
  "search.allTypes": "Tous les types",
  "search.type.hotel": "Hôtel",
  "search.type.apartment": "Appartement",
  "search.type.villa": "Villa",
  "search.type.hostel": "Auberge",
  "search.type.guesthouse": "Maison d'hôtes",
  "search.type.riad": "Riad",
  "search.type.resort": "Resort",
  "search.travelers": "Voyageurs",
  "search.travelersPlaceholder": "Pers.",
  "search.amenity": "Équipement",
  "search.amenity.all": "Tous",
  "search.sort": "Tri",
  "search.sort.rating": "Mieux notés",
  "search.sort.priceAsc": "Prix croissant",
  "search.sort.priceDesc": "Prix décroissant",
  "search.priceMin": "Prix min.",
  "search.priceMax": "Prix max.",
  "search.button": "Rechercher",
  "search.resultsCount": "résultat",
  "search.resultsPlural": "résultats",
  "search.pageOf": "sur",
  "search.pageShort": "page",
  "search.prev": "Précédent",
  "search.next": "Suivant",
  "search.empty": "Aucun hébergement ne correspond à vos critères.",
  "search.currencyHint": "Filtrage dans votre devise d'affichage.",
  "amenity.pool": "Piscine",
  "amenity.restaurant": "Restaurant",
  "search.accommodationsIn": "Hébergements à",
  "search.allAccommodations": "Tous les hébergements",
  "search.noResults": "Aucun résultat",
  "search.noneInCity": "Aucun hébergement trouvé à \"{city}\". Essayez une autre destination.",
  "search.startSearch": "Commencez votre recherche pour trouver des hébergements.",
  "search.backHome": "Retour à l'accueil",
  "search.pagination": "Pagination des résultats",
  // Actions communes
  "action.save": "Enregistrer",
  "action.saved": "Modifications enregistrées",
  "action.cancel": "Annuler",
  "action.confirm": "Confirmer",
  "action.back": "Retour",
  "action.loading": "Chargement…",
  "action.close": "Fermer",
  "action.send": "Envoyer",
  // Auth
  "auth.login": "Connexion",
  "auth.register": "Inscription",
  "auth.email": "Adresse e-mail",
  "auth.password": "Mot de passe",
  "auth.firstName": "Prénom",
  "auth.lastName": "Nom",
  "auth.loginButton": "Se connecter",
  "auth.registerButton": "Créer mon compte",
  "auth.logoutButton": "Se déconnecter",
  "auth.forgotPassword": "Mot de passe oublié ?",
  "auth.noAccount": "Pas encore de compte ?",
  "auth.hasAccount": "Déjà un compte ?",
  "auth.signupLink": "Inscrivez-vous",
  "auth.loginLink": "Connectez-vous",
  // Fiche hébergement
  "property.about": "À propos",
  "property.amenities": "Équipements",
  "property.reviews": "Avis",
  "property.rooms": "Chambres disponibles",
  "property.noRooms": "Aucune chambre disponible pour le moment",
  "property.cancellationFree": "annulation gratuite",
  "property.cancellationNonRefundable": "non remboursable",
  "property.cancellationSeeRate": "voir le tarif",
  "property.newPartner": "Nouveau partenaire — pas encore d'avis",
  "property.reviewPlural": "avis",
  "property.hostReply": "Réponse de l'hébergement",
  "property.verifiedReviews": "Avis vérifiés",
  "property.policies": "Politiques",
  // Réservation / tunnel
  "reservation.title": "Finaliser la réservation",
  "reservation.continuePayment": "Continuer vers le paiement",
  "reservation.totalPaid": "Total payé",
  "reservation.amountToConfirm": "Montant à confirmer",
  "reservation.allInclusive": "tout inclus",
  "reservation.nights": "nuit",
  "reservation.nightsPlural": "nuits",
  "reservation.subtotal": "Sous-total",
  "reservation.taxes": "Taxes",
  "reservation.useWallet": "Utiliser mon crédit wallet",
  "reservation.guestTitle": "Vous réservez en tant qu'invité",
  "reservation.bookingConfirmed": "Réservation confirmée",
  "reservation.refLabel": "Référence",
  "reservation.stepSelection": "Votre sélection",
  "reservation.stepInfo": "Vos informations",
  "reservation.stepPayment": "Paiement",
  "reservation.stepDone": "Confirmé !",
  "reservation.yourInfo": "Vos informations",
  "reservation.taxesFees": "Taxes et frais",
  "reservation.walletAvailable": "Utiliser mon crédit wallet",
  "reservation.walletAvail": "dispo",
  "reservation.guestMode": "Mode invité",
  "reservation.guestModeDesc": "vous réservez sans créer de compte.",
  // T-152 (audit n°24) : reprise de paiement depuis /mes-reservations
  "reservation.resumeError": "Impossible de charger la réservation",
  "reservation.cannotResume": "Cette réservation n'est plus en attente de paiement.",
  "reservation.alreadyConfirmed": "Cette réservation est déjà confirmée.",
  "reservation.payPending": "Paiement en attente",
  "reservation.seeBookings": "Voir mes réservations",
  "bookings.title": "Mes réservations",
  "bookings.empty": "Vous n'avez encore aucune réservation.",
  "bookings.upcoming": "À venir",
  "bookings.past": "Terminées",
  "bookings.total": "Total",
  "bookings.viewProperty": "Voir l'hébergement",
  "bookings.leaveReview": "Laisser un avis",
  "bookings.fee": "Frais",
  "bookings.refund": "Remboursement",
  "bookings.refundDone": "effectué",
  "bookings.refundPending": "en cours",
  "bookings.refundNone": "non requis",
  "status.pending": "En attente",
  "status.confirmed": "Confirmée",
  "status.cancelled": "Annulée",
  "status.completed": "Terminée",
  "status.no_show": "No-show",
  "common.noBooking": "Aucune réservation",
  "bookings.subtitle": "Retrouvez toutes vos réservations MyBestBooking",
  "bookings.emptyDesc": "Vous n'avez pas encore effectué de réservation. Trouvez votre prochain séjour !",
  "bookings.explore": "Explorer les hébergements",
  // T-152 (audit n°24) : actions pending + état avis
  "bookings.payNow": "Payer maintenant",
  "bookings.payPending": "Paiement en attente",
  "bookings.reviewPublished": "Avis publié",
  "bookings.reviewPending": "En attente de modération",
  "bookings.reviewSubmitted": "Avis soumis",
  "bookings.alreadyReviewed": "Vous avez déjà publié un avis pour cette réservation.",
  "bookings.yourRating": "Votre note",
  "bookings.reviewBack": "Retour à mes réservations",
  "bookings.viewAccommodation": "Voir l'hébergement",
  // Compte
  "account.personalInfo": "Informations personnelles",
  "account.phone": "Téléphone",
  "account.country": "Pays (ISO-2)",
  "account.language": "Langue",
  "account.currency": "Devise",
  "account.timezone": "Fuseau horaire",
  "account.avatar": "Photo de profil (URL)",
  "account.avatarHint": "Laissez vide pour afficher vos initiales. URL d'image publique.",
  "account.wallet": "Crédit wallet",
  "account.security": "Sécurité",
  "account.notifications": "Notifications",
  "account.password": "Mot de passe",
  "account.walletHint": "Cochez « Utiliser mon crédit wallet » sur la page de réservation.",
  // Favoris
  "fav.title": "Mes favoris",
  "fav.empty": "Vous n'avez pas encore de favoris.",
  "fav.priceAlerts": "Vos alertes de prix",
  "fav.countOne": "hébergement sauvegardé",
  "fav.countMany": "hébergements sauvegardés",
  "fav.emptyTitle": "Aucun favori",
  "fav.emptyDesc": "Sauvegardez vos hébergements préférés pour les retrouver facilement",
  "fav.alertsManaged": "Vos alertes prix sont gérées ci-dessus. Ajoutez-en depuis la fiche d'un hébergement (bouton « Suivre le prix »).",
  "fav.priceAlertsTitle": "Alertes prix",
  "fav.priceAlertsDesc": "Activez les alertes pour être notifié quand le prix d'un de vos favoris baisse.",
  // Messages
  "messages.empty": "Vos conversations avec les hébergeurs apparaîtront ici. Utilisez « Contacter l'hôte » sur une fiche ou depuis une réservation.",
  "messages.title": "Messages",
  "dash.overview": "Tableau de bord",
  "dash.properties": "Hébergements",
  "dash.rooms": "Chambres",
  "dash.bookings": "Réservations",
  "dash.reviews": "Avis",
  "dash.messages": "Messages",
  "dash.analytics": "Statistiques",
  "dash.billing": "Facturation",
  "dash.users": "Utilisateurs",
  "dash.promotions": "Promotions",
  "dash.audit": "Journal d'audit",
  "dash.settings": "Paramètres",
  "dash.help": "Aide",
  "dash.area": "Espace hébergeur",
  "dash.roleAdmin": "Administrateur",
  "dash.roleHost": "Hébergeur",
  "home.heroTitle1": "Réservez mieux.",
  "home.heroTitle2": "Voyagez plus.",
  "home.heroSub1": "Trouvez les meilleurs hébergements au meilleur prix.",
  "home.heroSub2": "Offres affichées, avis vérifiés et frais présentés avant confirmation.",
  "home.whereGo": "Où voulez-vous aller ?",
  "home.travelerOne": "voyageur",
  "home.travelerMany": "voyageurs",
  "home.search": "Rechercher",
  "home.trustPrice": "Prix vérifiés au paiement",
  "home.trustReviews": "Avis vérifiés",
  "home.trustNoFees": "0 frais cachés",
  "home.featuredTitle": "🔥 Hébergements populaires",
  "home.featuredSub": "Les mieux notés par nos voyageurs",
  "home.seeAll": "Voir tout",
  "home.seeAllProperties": "Voir tous les hébergements",
  "home.destTitle": "🌍 Destinations tendance",
  "home.discover": "Découvrir",
  "home.whyTitle": "✦ Pourquoi choisir MyBestBooking ?",
  "home.whyPriceTitle": "Prix vérifiés au paiement",
  "home.whyPriceBody": "Trouvé moins cher ailleurs ? On vous rembourse la différence. C'est notre engagement.",
  "home.whyReviewTitle": "Avis 100% Vérifiés",
  "home.whyReviewBody": "Seuls les voyageurs ayant réservé et séjourné peuvent laisser un avis. Zéro faux avis.",
  "home.whySupportTitle": "Support par email",
  "home.whySupportBody": "Une équipe humaine disponible à tout moment pour vous aider. Pas des bots.",
  "home.rewardsTitle": "Les vrais avantages, dès votre 1ère réservation",
  "home.rewardsBody": "Jusqu'à -20% sur les hébergements BestRewards et cashback Ambassador après séjour terminé.",
  "home.learnMore": "En savoir plus",
  "home.joinFree": "Rejoindre gratuitement",
  "home.firstVisit": "🚀 Première visite ?",
  "home.firstVisitBody": "Pour voir l'application en action avec des données de démonstration, cliquez sur le bouton ci-dessous.",
  "home.loadDemo": "Charger les données de démo",
  "notfound.title": "Page introuvable",
  "notfound.body": "Cette page n'existe pas ou plus. Peut-être avez-vous suivi un lien devenu obsolète ?",
  "notfound.home": "Retour à l'accueil",
} as const;

export type UiStringKey = keyof typeof FR;

const EN: Record<UiStringKey, string> = {
  "price.from": "From",
  "price.perNight": "/night",
  "price.unavailable": "Price unavailable",
  "price.fromShort": "From",
  "price.perNightLong": "per night",
  "price.convertedNote": "Indicative conversion · charged in",
  "book.seeAvailability": "See availability",
  "book.noRoom": "No room available",
  "book.checkIn": "Check-in",
  "book.checkOut": "Check-out",
  "book.adults": "Adults",
  "book.children": "Children",
  "book.cancelShown": "✓ Cancellation policy shown before confirmation",
  "fav.add": "Add to favorites",
  "fav.added": "Added to favorites",
  "card.reviews": "reviews",
  "card.viewRooms": "View rooms →",
  "contact.host": "Contact the host",
  "contact.question": "Ask the host a question before booking",
  "contact.error": "Could not start the conversation",
  "contact.notFound": "Conversation not found",
  "nav.login": "Log in",
  "nav.myAccount": "My account",
  "nav.bookings": "My bookings",
  "nav.favorites": "My favorites",
  "nav.messages": "Messages",
  "nav.dashboard": "Dashboard",
  "nav.logout": "Log out",
  "nav.search": "Search",
  "nav.bestrewards": "BestRewards",
  "nav.help": "Help",
  "nav.accommodations": "Accommodations",
  "nav.signup": "Sign up",
  "nav.userMenu": "User menu",
  "nav.openMenu": "Open menu",
  "nav.closeMenu": "Close menu",
  "footer.discover": "Discover",
  "footer.searchAccommodation": "Search accommodation",
  "footer.helpCenter": "Help center",
  "footer.travelers": "Travelers",
  "footer.messaging": "Messages",
  "footer.hosts": "Hosts",
  "footer.addProperty": "List my property",
  "footer.hostArea": "Host dashboard",
  "footer.createAccount": "Create an account",
  "footer.contact": "Contact",
  "footer.tagline": "Book better. Travel further.",
  "footer.legal": "Legal notice",
  "footer.privacy": "Privacy",
  "footer.rights": "© 2025 MyBestBooking — All rights reserved",
  "search.title": "Accommodation search",
  "search.destination": "Destination",
  "search.destinationPlaceholder": "City or accommodation",
  "search.arrival": "Check-in",
  "search.departure": "Check-out",
  "search.type": "Type",
  "search.allTypes": "All types",
  "search.type.hotel": "Hotel",
  "search.type.apartment": "Apartment",
  "search.type.villa": "Villa",
  "search.type.hostel": "Hostel",
  "search.type.guesthouse": "Guesthouse",
  "search.type.riad": "Riad",
  "search.type.resort": "Resort",
  "search.travelers": "Travelers",
  "search.travelersPlaceholder": "Guests",
  "search.amenity": "Amenity",
  "search.amenity.all": "All",
  "search.sort": "Sort",
  "search.sort.rating": "Top rated",
  "search.sort.priceAsc": "Price: low to high",
  "search.sort.priceDesc": "Price: high to low",
  "search.priceMin": "Min price",
  "search.priceMax": "Max price",
  "search.button": "Search",
  "search.resultsCount": "result",
  "search.resultsPlural": "results",
  "search.pageOf": "of",
  "search.pageShort": "page",
  "search.prev": "Previous",
  "search.next": "Next",
  "search.empty": "No accommodation matches your criteria.",
  "search.currencyHint": "Filtering in your display currency.",
  "amenity.pool": "Pool",
  "amenity.restaurant": "Restaurant",
  "search.accommodationsIn": "Accommodation in",
  "search.allAccommodations": "All accommodations",
  "search.noResults": "No results",
  "search.noneInCity": "No accommodation found in \"{city}\". Try another destination.",
  "search.startSearch": "Start your search to find accommodation.",
  "search.backHome": "Back to home",
  "search.pagination": "Results pagination",
  "action.save": "Save",
  "action.saved": "Changes saved",
  "action.cancel": "Cancel",
  "action.confirm": "Confirm",
  "action.back": "Back",
  "action.loading": "Loading…",
  "action.close": "Close",
  "action.send": "Send",
  "auth.login": "Login",
  "auth.register": "Sign up",
  "auth.email": "Email address",
  "auth.password": "Password",
  "auth.firstName": "First name",
  "auth.lastName": "Last name",
  "auth.loginButton": "Log in",
  "auth.registerButton": "Create my account",
  "auth.logoutButton": "Log out",
  "auth.forgotPassword": "Forgot password?",
  "auth.noAccount": "No account yet?",
  "auth.hasAccount": "Already have an account?",
  "auth.signupLink": "Sign up",
  "auth.loginLink": "Log in",
  "property.about": "About",
  "property.amenities": "Amenities",
  "property.reviews": "Reviews",
  "property.rooms": "Available rooms",
  "property.noRooms": "No room available at the moment",
  "property.cancellationFree": "free cancellation",
  "property.cancellationNonRefundable": "non-refundable",
  "property.cancellationSeeRate": "see rate",
  "property.newPartner": "New partner — no reviews yet",
  "property.reviewPlural": "reviews",
  "property.hostReply": "Host reply",
  "property.verifiedReviews": "Verified reviews",
  "property.policies": "Policies",
  "reservation.title": "Complete your booking",
  "reservation.continuePayment": "Continue to payment",
  "reservation.totalPaid": "Total paid",
  "reservation.amountToConfirm": "Amount to confirm",
  "reservation.allInclusive": "all taxes included",
  "reservation.nights": "night",
  "reservation.nightsPlural": "nights",
  "reservation.subtotal": "Subtotal",
  "reservation.taxes": "Taxes",
  "reservation.useWallet": "Use my wallet credit",
  "reservation.guestTitle": "You are booking as a guest",
  "reservation.bookingConfirmed": "Booking confirmed",
  "reservation.refLabel": "Reference",
  "reservation.stepSelection": "Your selection",
  "reservation.stepInfo": "Your details",
  "reservation.stepPayment": "Payment",
  "reservation.stepDone": "Confirmed!",
  "reservation.yourInfo": "Your details",
  "reservation.taxesFees": "Taxes and fees",
  "reservation.walletAvailable": "Use my wallet credit",
  "reservation.walletAvail": "available",
  "reservation.guestMode": "Guest mode",
  "reservation.guestModeDesc": "you are booking without creating an account.",
  // T-152 (audit n°24) : reprise de paiement depuis /mes-reservations
  "reservation.resumeError": "Unable to load the booking",
  "reservation.cannotResume": "This booking is no longer awaiting payment.",
  "reservation.alreadyConfirmed": "This booking is already confirmed.",
  "reservation.payPending": "Payment pending",
  "reservation.seeBookings": "View my bookings",
  "bookings.title": "My bookings",
  "bookings.empty": "You don't have any bookings yet.",
  "bookings.upcoming": "Upcoming",
  "bookings.past": "Completed",
  "bookings.total": "Total",
  "bookings.viewProperty": "View property",
  "bookings.leaveReview": "Leave a review",
  "bookings.fee": "Fee",
  "bookings.refund": "Refund",
  "bookings.refundDone": "done",
  "bookings.refundPending": "pending",
  "bookings.refundNone": "not required",
  "status.pending": "Pending",
  "status.confirmed": "Confirmed",
  "status.cancelled": "Cancelled",
  "status.completed": "Completed",
  "status.no_show": "No-show",
  "common.noBooking": "No bookings",
  "bookings.subtitle": "Find all your MyBestBooking bookings",
  "bookings.emptyDesc": "You haven't made any booking yet. Find your next stay!",
  "bookings.explore": "Explore accommodations",
  // T-152 (audit n°24) : actions pending + état avis
  "bookings.payNow": "Pay now",
  "bookings.payPending": "Payment pending",
  "bookings.reviewPublished": "Review published",
  "bookings.reviewPending": "Pending moderation",
  "bookings.reviewSubmitted": "Review submitted",
  "bookings.alreadyReviewed": "You have already published a review for this booking.",
  "bookings.yourRating": "Your rating",
  "bookings.reviewBack": "Back to my bookings",
  "bookings.viewAccommodation": "View accommodation",
  "account.personalInfo": "Personal information",
  "account.phone": "Phone",
  "account.country": "Country (ISO-2)",
  "account.language": "Language",
  "account.currency": "Currency",
  "account.timezone": "Time zone",
  "account.avatar": "Profile photo (URL)",
  "account.avatarHint": "Leave empty to show your initials. Public image URL.",
  "account.wallet": "Wallet credit",
  "account.security": "Security",
  "account.notifications": "Notifications",
  "account.password": "Password",
  "account.walletHint": "Tick “Use my wallet credit” on the booking page.",
  "fav.title": "My favorites",
  "fav.empty": "You don't have any favorites yet.",
  "fav.priceAlerts": "Your price alerts",
  "fav.countOne": "saved accommodation",
  "fav.countMany": "saved accommodations",
  "fav.emptyTitle": "No favorites",
  "fav.emptyDesc": "Save your favorite accommodations to find them easily",
  "fav.alertsManaged": "Your price alerts are managed above. Add one from an accommodation page (“Track price” button).",
  "fav.priceAlertsTitle": "Price alerts",
  "fav.priceAlertsDesc": "Enable alerts to be notified when the price of a favorite drops.",
  "messages.empty": "Your conversations with hosts will appear here. Use “Contact the host” on a listing or from a booking.",
  "messages.title": "Messages",
  "dash.overview": "Dashboard",
  "dash.properties": "Properties",
  "dash.rooms": "Rooms",
  "dash.bookings": "Bookings",
  "dash.reviews": "Reviews",
  "dash.messages": "Messages",
  "dash.analytics": "Analytics",
  "dash.billing": "Billing",
  "dash.users": "Users",
  "dash.promotions": "Promotions",
  "dash.audit": "Audit log",
  "dash.settings": "Settings",
  "dash.help": "Help",
  "dash.area": "Host area",
  "dash.roleAdmin": "Administrator",
  "dash.roleHost": "Host",
  "home.heroTitle1": "Book better.",
  "home.heroTitle2": "Travel further.",
  "home.heroSub1": "Find the best stays at the best price.",
  "home.heroSub2": "Clear offers, verified reviews and fees shown before you confirm.",
  "home.whereGo": "Where do you want to go?",
  "home.travelerOne": "traveler",
  "home.travelerMany": "travelers",
  "home.search": "Search",
  "home.trustPrice": "Prices verified at checkout",
  "home.trustReviews": "Verified reviews",
  "home.trustNoFees": "No hidden fees",
  "home.featuredTitle": "🔥 Popular accommodations",
  "home.featuredSub": "Top rated by our travelers",
  "home.seeAll": "See all",
  "home.seeAllProperties": "See all accommodations",
  "home.destTitle": "🌍 Trending destinations",
  "home.discover": "Discover",
  "home.whyTitle": "✦ Why choose MyBestBooking?",
  "home.whyPriceTitle": "Prices verified at checkout",
  "home.whyPriceBody": "Found it cheaper elsewhere? We refund the difference. That's our promise.",
  "home.whyReviewTitle": "Avis 100% Vérifiés",
  "home.whyReviewBody": "Only travelers who booked and stayed can leave a review. Zero fake reviews.",
  "home.whySupportTitle": "Email support",
  "home.whySupportBody": "A real team available anytime to help you. No bots.",
  "home.rewardsTitle": "Real benefits from your very first booking",
  "home.rewardsBody": "Up to -20% on BestRewards stays and Ambassador cashback after your completed trip.",
  "home.learnMore": "Learn more",
  "home.joinFree": "Join for free",
  "home.firstVisit": "🚀 First visit?",
  "home.firstVisitBody": "To see the app in action with demo data, click the button below.",
  "home.loadDemo": "Load demo data",
  "notfound.title": "Page not found",
  "notfound.body": "This page does not exist anymore. Maybe you followed an outdated link?",
  "notfound.home": "Back to home",
};

export function isUiLocale(locale: string | null | undefined): locale is UiLocale {
  return locale === "fr" || locale === "en";
}

export function uiStrings(locale: string | null | undefined): Record<UiStringKey, string> {
  const loc = isUiLocale(locale) ? locale : "fr";
  return loc === "en" ? EN : FR;
}

/** Accès pratique : renvoie une fonction `t(key)` pour une langue donnée. */
export function makeT(locale: string | null | undefined): (key: UiStringKey) => string {
  const dict = uiStrings(locale);
  return (key: UiStringKey) => dict[key];
}
