/**
 * T-132/T-134 — Libellés d'interface localisés (FR par défaut, EN).
 *
 * L'arabe (ar) reste hors périmètre V1 (pas de dictionnaire RTL) : on
 * retombe sur le français. Ce dictionnaire couvre l'interface client
 * (navigation, recherche, fiche, tunnel de réservation, compte, auth…).
 * Utilisable côté serveur (RSC) comme côté client.
 */

export type UiLocale = "fr" | "en";

const FR = {
  // Prix / cartes
  "price.from": "Dès",
  "price.perNight": "/nuit",
  "price.unavailable": "Prix indisponible",
  "price.fromShort": "À partir de",
  "price.perNightLong": "par nuit",
  "price.convertedNote": "Conversion indicative · paiement en",
  // Fiche / carte
  "book.seeAvailability": "Voir les disponibilités",
  "book.noRoom": "Aucune chambre disponible",
  "book.reserve": "Réserver",
  "review.helpful": "Utile",
  "review.thanks": "Merci",
  "review.helpfulLogin": "— connexion requise",
  "priceAlert.followBase": "Suivre le prix de base",
  "priceAlert.followStay": "Suivre le prix de ce séjour",
  "headerActions.favoriteAdd": "Ajouter aux favoris",
  "headerActions.favoriteRemove": "Retirer des favoris",
  "headerActions.favoriteAdded": "Ajouté à vos favoris",
  "headerActions.favoriteRemoved": "Retiré de vos favoris",
  "headerActions.share": "Partager",
  "headerActions.shareLabel": "Partager cet hébergement",
  "headerActions.linkCopied": "Lien copié",
  "wishlist.copy": "Copié !",
  "wishlist.share": "Partager",
  "priceAlert.title": "Alertes prix",
  "priceAlert.empty": "Vous n'avez pas encore d'alerte prix. Cliquez sur « Suivre le prix » depuis la fiche d'un hébergement.",
  "priceAlert.belowPrefix": "Alerte si le prix descend sous",
  "priceAlert.confirmRemove": "Supprimer cette alerte ?",
  "priceAlert.removeLabel": "Supprimer l'alerte",
  "priceAlert.loading": "Chargement…",
  "privacy.meta.title": "Politique de confidentialité",
  "privacy.meta.description": "Politique de traitement des données personnelles et de cookies de MyBestBooking (RGPD).",
  "legal.meta.title": "Mentions légales",
  "legal.meta.description": "Mentions légales, conditions générales d'utilisation et de vente de MyBestBooking.",
  "bestrewards.meta.title": "BestRewards — programme fidélité",
  "bestrewards.meta.description": "Cumulez des séjours terminés et débloquez des réductions BestRewards et le cashback Ambassador.",
  "reservation.meta.title": "Finaliser ma réservation",
  "reservation.meta.description": "Vérifiez votre sélection, votre identité et procédez au paiement sécurisé.",
  "bestrewards.hero": "Les vrais avantages, dès votre 1ère réservation.<br/>Rejoignez le programme de fidélité MyBestBooking.",
  "bestrewards.join": "Rejoindre gratuitement",
  "bestrewards.yourLevel": "Votre niveau :",
  "bestrewards.yourLevelBadge": "Votre niveau",
  "bestrewards.how": "Comment ça marche ?",
  "bestrewards.how1Title": "Inscrivez-vous",
  "bestrewards.how1Desc": "C'est gratuit et instantané. Vous êtes immédiatement Level 1 Explorer.",
  "bestrewards.how2Title": "Réservez",
  "bestrewards.how2Desc": "Chaque réservation confirmée compte. Plus vous voyagez, plus vous montez en niveau.",
  "bestrewards.how3Title": "Profitez",
  "bestrewards.how3Desc": "Utilisez vos réductions BestRewards et, au niveau Ambassador, votre cashback wallet.",
  "bestrewards.levelsTitle": "Les 3 niveaux BestRewards",
  "bestrewards.faqTitle": "Questions fréquentes",
  "bestrewards.faq1Q": "Comment rejoindre BestRewards ?",
  "bestrewards.faq1A": "C'est automatique ! Dès votre inscription sur MyBestBooking, vous êtes Level 1 Explorer et bénéficiez immédiatement de la réduction configurée sur les hébergements BestRewards.",
  "bestrewards.faq2Q": "Comment monter de niveau ?",
  "bestrewards.faq2A": "Chaque séjour terminé compte. Après {n2} séjours, vous passez Level 2 Voyageur. Après {n3} séjours, vous atteignez Level 3 Ambassador.",
  "bestrewards.faq3Q": "Les réductions sont-elles cumulables ?",
  "bestrewards.faq3A": "Les réductions BestRewards s'appliquent automatiquement sur les hébergements éligibles (badge 💎). Elles peuvent se cumuler avec certaines promotions selon les partenaires.",
  "bestrewards.faq4Q": "Comment fonctionne le cashback Ambassador ?",
  "bestrewards.faq4A": "Au Level 3, vous gagnez 5% de cashback sur chaque réservation, crédité directement sur votre wallet MyBestBooking. Ce solde est utilisable sur vos prochaines réservations.",
  "bestrewards.faq5Q": "Mon niveau peut-il expirer ?",
  "bestrewards.faq5A": "Votre niveau progresse après chaque séjour terminé. Les règles de durée de validité ne sont pas encore proposées ; votre niveau n'expire donc pas automatiquement.",
  "bestrewards.ctaTitle": "Prêt à profiter des avantages ?",
  "bestrewards.ctaDesc": "Rejoignez des milliers de voyageurs qui économisent avec BestRewards",
  "bestrewards.ctaButton": "Créer mon compte gratuit",
  "bestrewards.level1Name": "Explorer",
  "bestrewards.level2Name": "Voyageur",
  "bestrewards.level3Name": "Ambassador",
  "bestrewards.requirement1": "Dès l'inscription",
  "bestrewards.requirementN": "{n} séjours terminés",
  "bestrewards.benefit1": "Réduction de {pct}% sur les hébergements BestRewards",
  "bestrewards.benefit2": "Suivi de votre niveau dans Mon compte",
  "bestrewards.benefit2Level2": "Tous les avantages Explorer",
  "bestrewards.benefitN": "Réduction de {pct}% niveau {level} sur BestRewards",
  "bestrewards.benefitCashback": "Cashback 5% en wallet après séjour",
  "bestrewards.benefit2Level3": "Tous les avantages Voyageur",
  "share.label": "Liste partagée",
  "share.countOne": "{count} hébergement",
  "share.countMany": "{count} hébergements",
  "share.empty": "Cette liste est vide pour le moment.",
  "share.meta.title": "{name} — Liste partagée",
  "share.meta.description": "Liste d'hébergements partagée sur MyBestBooking.",
  "reservation.missingInfo": "Informations de réservation manquantes",
  "reservation.yourSelection": "✦ Votre sélection",
  "reservation.arrivalTime": "Heure d'arrivée estimée",
  "reservation.unspecified": "Non spécifiée",
  "reservation.securePaymentTitle": "Paiement en ligne sécurisé",
  "reservation.securePaymentBody": "Les données de carte sont saisies directement dans l'interface du prestataire de paiement ; MyBestBooking ne les enregistre jamais.",
  "reservation.confirmAfterPayment": "Votre réservation ne sera confirmée qu'après confirmation effective du paiement.",
  "reservation.demoMode": "Mode démonstration : aucun débit réel n'a été effectué.",
  "reservation.resumePayment": "Reprendre le même paiement",
  "reservation.activateAccess": "Activez votre accès depuis l'email envoyé, puis reconnectez-vous pour reprendre ce paiement sans recréer la réservation.",
  "reservation.viewBookings": "Voir mes réservations",
  "reservation.backHome": "Retour à l'accueil",
  "reservation.createAccount": "Créer un compte plutôt",
  "reservation.priceConfirmed": "Prix confirmé avant paiement",
  "reservation.securePayment": "Paiement sécurisé",
  "reservation.loading": "Chargement…",
  "reservation.adults": "Adultes",
  "reservation.children": "Enfants",
  "reservation.ratePlan": "Tarif et avantages",
  "reservation.standardRate": "Tarif standard",
  "reservation.breakfastIncluded": " · petit-déjeuner inclus",
  "reservation.adultsOption": "{n} adulte",
  "reservation.adultsOptionPlural": "{n} adultes",
  "reservation.childrenOption": "{n} enfant",
  "reservation.childrenOptionPlural": "{n} enfants",
  "reservation.walletReductionNote": "Sera appliqué en réduction sur le total, plafonné au montant restant. Le solde du wallet est libellé en euros.",
  "reservation.walletLabel": "Wallet",
  "reservation.totalLabel": "Total",
  "reservation.bookingError": "Erreur lors de la réservation",
  "reservation.paymentPendingRetry": "Le paiement reste en préparation. Réessayez dans quelques instants.",
  "reservation.checkInDate": "Date d'arrivée",
  "reservation.checkOutDate": "Date de départ",
  "reservation.policyPrefix": "Politique : {policy}",
  "reservation.breakfastIncludedCaps": " · Petit-déjeuner inclus",
  "reservation.firstName": "Prénom",
  "reservation.phone": "Téléphone",
  "reservation.residenceCountry": "Pays de résidence",
  "reservation.unitedStates": "États-Unis",
  "reservation.specialRequests": "Demandes spéciales (optionnel)",
  "reservation.specialRequestsPlaceholder": "Ex: chambre calme, lit bébé, arrivée tardive...",
  "reservation.paymentConfirming": "Paiement en cours de confirmation",
  "reservation.confirmed": "🎉 C'est confirmé !",
  "reservation.paymentTransmitted": "Votre demande de paiement a été transmise. La réservation sera confirmée dès la réponse sécurisée du prestataire.",
  "reservation.confirmationEmail": "📧 Vous recevrez la confirmation définitive à l'issue du paiement.",
  "reservation.confirmationEmailSent": "Un email de confirmation vous sera envoyé.",
  "reservation.roomLabel": "Chambre",
  "reservation.promoCode": "Code {code}",
  "priceAlert.alertIf": "M'alerter si",
  "priceAlert.totalNights": "le total des nuits de ce séjour (hors taxes)",
  "priceAlert.basePrice": "le prix de base",
  "priceAlert.descendsUnder": "descend sous :",
  "bookingCard.conversionTooltip": "Conversion indicative, taux figés. Le paiement reste en devise de l'hébergement.",
  "meta.notFound": "Hébergement introuvable",
  "meta.bookBestPrice": "Réservez au meilleur prix.",
  "review.back": "Retour à mes réservations",
  "review.title": "Partager votre expérience",
  "review.verifiedModerated": "Votre séjour est vérifié. Votre avis sera publié après modération.",
  "review.verifiedImmediate": "Votre séjour est déjà vérifié : votre avis sera publié immédiatement après envoi.",
  "review.overall": "Note globale :",
  "review.subtitle": "Notes par critère",
  "review.subtitleHint": "(facultatif — égales à la note globale par défaut)",
  "review.ratingFor": "Note pour",
  "review.travelerType": "Type de voyage",
  "review.traveler.leisure": "Loisirs",
  "review.traveler.solo": "Solo",
  "review.traveler.couple": "Couple",
  "review.traveler.family": "Famille",
  "review.traveler.group": "Groupe",
  "review.traveler.business": "Affaires",
  "review.positiveLabel": "Ce que vous avez aimé",
  "review.positivePlaceholder": "Parlez de votre séjour...",
  "review.negativeLabel": "Ce qui pourrait être amélioré",
  "review.negativePlaceholder": "Facultatif",
  "review.publish": "Publier mon avis",
  "review.sendError": "Impossible d'envoyer votre avis",
  "review.genericError": "Erreur lors de l'envoi",
  "review.sentModerated": "Avis envoyé — en attente de modération",
  "review.sentPublished": "Merci, votre avis est publié",
  "review.cleanliness": "Propreté",
  "review.comfort": "Confort",
  "review.location": "Emplacement",
  "review.facilities": "Équipements",
  "review.staff": "Accueil / service",
  "review.value": "Rapport qualité-prix",
  "crumb.home": "Accueil",
  "crumb.properties": "Hébergements",
  "badge.eco": "🌱 Éco",
  "trust.title": "Informations MyBestBooking",
  "trust.priceChecked": "Prix vérifié au paiement",
  "trust.feesShown": "Frais affichés avant confirmation",
  "trust.supportEmail": "Contact support par email",
  "help.heroTitle": "Comment pouvons-nous vous aider ?",
  "help.heroSubtitle": "Recherchez une réponse ou contactez notre équipe par email.",
  "help.searchPlaceholder": "Rechercher dans l'aide…",
  "help.articles": "Articles",
  "help.noResults": "Aucun article ne correspond à votre recherche.",
  "help.selectArticle": "Sélectionnez un article.",
  "help.writeSupport": "Écrire au support",
  "help.mailSubject": "Aide MyBestBooking",
  "help.meta.title": "Aide et FAQ",
  "help.meta.description": "Trouvez des réponses concrètes à vos questions de réservation, paiement, compte et hébergement.",
  "book.checkIn": "Arrivée",
  "book.checkOut": "Départ",
  "book.adults": "Adultes",
  "book.children": "Enfants",
  "book.cancelShown": "✓ Conditions d'annulation affichées avant confirmation",
  "book.cancel.free": "Annulation gratuite",
  "book.cancel.flexible": "Annulation gratuite jusqu'à 24 h avant l'arrivée, puis 100 %",
  "book.cancel.moderate": "Annulation gratuite jusqu'à 5 jours avant, puis 50 % (100 % à moins de 24 h)",
  "book.cancel.strict": "Annulation gratuite jusqu'à 30 jours avant, puis 50 % (100 % à moins de 7 jours)",
  "book.cancel.nonRefundable": "Non remboursable",
  "fav.add": "Ajouter aux favoris",
  "fav.added": "Ajouté aux favoris",
  "fav.remove": "Retirer des favoris",
  "card.reviews": "avis",
  "card.viewRooms": "Voir les chambres →",
  // Contact hôte
  "contact.host": "Contacter l'hôte",
  "contact.question": "Poser une question à l'hôte avant de réserver",
  "contact.error": "Impossible de démarrer la conversation",
  "contact.notFound": "Conversation introuvable",
  // Navigation
  "nav.login": "Se connecter",
  "nav.myAccount": "Mon compte",
  "nav.bookings": "Mes réservations",
  "nav.favorites": "Mes favoris",
  "nav.messages": "Messages",
  "nav.dashboard": "Dashboard",
  "nav.logout": "Déconnexion",
  "nav.search": "Recherche",
  "nav.bestrewards": "BestRewards",
  "nav.help": "Aide",
  "nav.accommodations": "Hébergements",
  "nav.signup": "S'inscrire",
  "nav.userMenu": "Menu utilisateur",
  "nav.openMenu": "Ouvrir le menu",
  "nav.closeMenu": "Fermer le menu",
  "nav.level": "Niveau",
  "nav.darkModeOn": "Activer le mode clair",
  "nav.darkModeOff": "Activer le mode sombre",
  "nav.unreadOne": "{n} message non lu",
  "nav.unreadMany": "{n} messages non lus",
  "nav.languageSaveError": "Impossible d'enregistrer la préférence",
  "nav.roleAdmin": "Administrateur",
  "nav.roleHost": "Hébergeur",
  "footer.discover": "Découvrir",
  "footer.searchAccommodation": "Rechercher un hébergement",
  "footer.helpCenter": "Centre d'aide",
  "footer.travelers": "Voyageurs",
  "footer.messaging": "Messagerie",
  "footer.hosts": "Hébergeurs",
  "footer.addProperty": "Ajouter mon hébergement",
  "footer.hostArea": "Espace hébergeur",
  "footer.createAccount": "Créer un compte",
  "footer.contact": "Contact",
  "footer.tagline": "Réservez mieux. Voyagez plus.",
  "footer.legal": "Mentions légales",
  "footer.privacy": "Confidentialité",
  "footer.rights": "© 2025 MyBestBooking — Tous droits réservés",
  // Recherche (formulaire)
  "search.title": "Recherche d'hébergements",
  "search.destination": "Destination",
  "search.destinationPlaceholder": "Ville ou hébergement",
  "search.arrival": "Arrivée",
  "search.departure": "Départ",
  "search.type": "Type",
  "search.allTypes": "Tous les types",
  "search.type.hotel": "Hôtel",
  "search.type.apartment": "Appartement",
  "search.type.villa": "Villa",
  "search.type.hostel": "Auberge",
  "search.type.guesthouse": "Maison d'hôtes",
  "search.type.riad": "Riad",
  "search.type.resort": "Resort",
  "search.travelers": "Voyageurs",
  "search.travelersPlaceholder": "Pers.",
  "search.amenity": "Équipement",
  "search.amenity.all": "Tous",
  "search.sort": "Tri",
  "search.sort.rating": "Mieux notés",
  "search.sort.priceAsc": "Prix croissant",
  "search.sort.priceDesc": "Prix décroissant",
  "search.priceMin": "Prix min.",
  "search.priceMax": "Prix max.",
  "search.button": "Rechercher",
  "search.resultsCount": "résultat",
  "search.resultsPlural": "résultats",
  "search.pageOf": "sur",
  "search.pageShort": "page",
  "search.prev": "Précédent",
  "search.next": "Suivant",
  "search.empty": "Aucun hébergement ne correspond à vos critères.",
  "search.currencyHint": "Filtrage dans votre devise d'affichage.",
  "amenity.pool": "Piscine",
  "amenity.restaurant": "Restaurant",
  "search.accommodationsIn": "Hébergements à",
  "search.allAccommodations": "Tous les hébergements",
  "search.noResults": "Aucun résultat",
  "search.noneInCity": "Aucun hébergement trouvé à \"{city}\". Essayez une autre destination.",
  "search.startSearch": "Commencez votre recherche pour trouver des hébergements.",
  "search.backHome": "Retour à l'accueil",
  "search.pagination": "Pagination des résultats",
  // T-153 (audit n°25, F) : bandeau affiché quand on arrive via
  // « Utiliser mon solde » (/mon-compte → /recherche?wallet=1).
  "search.walletBanner": "Vous avez {amount} de crédits BestRewards. Pensez à cocher « Utiliser mes crédits » au paiement pour les déduire de votre séjour.",
  // Actions communes
  "action.save": "Enregistrer",
  "action.saved": "Modifications enregistrées",
  "action.cancel": "Annuler",
  "action.confirm": "Confirmer",
  "action.back": "Retour",
  "action.loading": "Chargement…",
  "action.close": "Fermer",
  "action.send": "Envoyer",
  // Auth
  "auth.login": "Connexion",
  "auth.register": "Inscription",
  "auth.email": "Adresse e-mail",
  "auth.password": "Mot de passe",
  "auth.firstName": "Prénom",
  "auth.lastName": "Nom",
  "auth.loginButton": "Se connecter",
  "auth.registerButton": "Créer mon compte",
  "auth.logoutButton": "Se déconnecter",
  "auth.forgotPassword": "Mot de passe oublié ?",
  "auth.noAccount": "Pas encore de compte ?",
  "auth.hasAccount": "Déjà un compte ?",
  "auth.signupLink": "Inscrivez-vous",
  "auth.loginLink": "Connectez-vous",
  // Fiche hébergement
  "property.about": "À propos",
  "property.amenities": "Équipements",
  "property.reviews": "Avis",
  "property.rooms": "Chambres disponibles",
  "property.noRooms": "Aucune chambre disponible pour le moment",
  "property.cancellationFree": "annulation gratuite",
  "property.cancellationNonRefundable": "non remboursable",
  "property.cancellationSeeRate": "voir le tarif",
  "property.newPartner": "Nouveau partenaire — pas encore d'avis",
  "property.reviewPlural": "avis",
  "property.hostReply": "Réponse de l'hébergement",
  "property.verifiedReviews": "Avis vérifiés",
  "property.policies": "Politiques",
  // Réservation / tunnel
  "reservation.title": "Finaliser la réservation",
  "reservation.continuePayment": "Continuer vers le paiement",
  "reservation.totalPaid": "Total payé",
  "reservation.amountToConfirm": "Montant à confirmer",
  "reservation.allInclusive": "tout inclus",
  "reservation.nights": "nuit",
  "reservation.nightsPlural": "nuits",
  "reservation.subtotal": "Sous-total",
  "reservation.taxes": "Taxes",
  "reservation.useWallet": "Utiliser mon crédit wallet",
  "reservation.guestTitle": "Vous réservez en tant qu'invité",
  "reservation.bookingConfirmed": "Réservation confirmée",
  "reservation.refLabel": "Référence",
  "reservation.stepSelection": "Votre sélection",
  "reservation.stepInfo": "Vos informations",
  "reservation.stepPayment": "Paiement",
  "reservation.stepDone": "Confirmé !",
  "reservation.yourInfo": "Vos informations",
  "reservation.bookedAs": "Réservé au nom de votre compte",
  "reservation.taxesFees": "Taxes et frais",
  "reservation.walletAvailable": "Utiliser mon crédit wallet",
  "reservation.walletAvail": "dispo",
  "reservation.guestMode": "Mode invité",
  "reservation.guestModeDesc": "vous réservez sans créer de compte.",
  // T-152 (audit n°24) : reprise de paiement depuis /mes-reservations
  "reservation.resumeError": "Impossible de charger la réservation",
  "reservation.cannotResume": "Cette réservation n'est plus en attente de paiement.",
  "reservation.alreadyConfirmed": "Cette réservation est déjà confirmée.",
  "reservation.payPending": "Paiement en attente",
  "reservation.seeBookings": "Voir mes réservations",
  "bookings.title": "Mes réservations",
  "bookings.empty": "Vous n'avez encore aucune réservation.",
  "bookings.upcoming": "À venir",
  "bookings.past": "Terminées",
  "bookings.total": "Total",
  "bookings.viewProperty": "Voir l'hébergement",
  "bookings.leaveReview": "Laisser un avis",
  "bookings.fee": "Frais",
  "bookings.refund": "Remboursement",
  "bookings.refundDone": "effectué",
  "bookings.refundPending": "en cours",
  "bookings.refundNone": "non requis",
  "status.pending": "En attente",
  "status.confirmed": "Confirmée",
  "status.cancelled": "Annulée",
  "status.completed": "Terminée",
  "status.no_show": "No-show",
  "common.noBooking": "Aucune réservation",
  "bookings.subtitle": "Retrouvez toutes vos réservations MyBestBooking",
  "bookings.emptyDesc": "Vous n'avez pas encore effectué de réservation. Trouvez votre prochain séjour !",
  "bookings.explore": "Explorer les hébergements",
  // T-152 (audit n°24) : actions pending + état avis
  "bookings.payNow": "Payer maintenant",
  "bookings.payPending": "Paiement en attente",
  "bookings.reviewPublished": "Avis publié",
  "bookings.reviewPending": "En attente de modération",
  "bookings.reviewSubmitted": "Avis soumis",
  "bookings.alreadyReviewed": "Vous avez déjà publié un avis pour cette réservation.",
  // T-153 (audit n°25, G) : badge explicatif sur les séjours passés dont
  // l'avis n'est pas encore ouvert.
  "bookings.reviewSoon": "Avis bientôt disponible — les avis sont ouverts après votre départ.",
  "bookings.yourRating": "Votre note",
  "bookings.reviewBack": "Retour à mes réservations",
  "bookings.viewAccommodation": "Voir l'hébergement",
  // Compte
  "account.personalInfo": "Informations personnelles",
  "account.phone": "Téléphone",
  "account.country": "Pays (ISO-2)",
  "account.language": "Langue",
  "account.currency": "Devise",
  "account.timezone": "Fuseau horaire",
  "account.avatar": "Photo de profil (URL)",
  "account.avatarHint": "Laissez vide pour afficher vos initiales. URL d'image publique.",
  "account.wallet": "Crédit wallet",
  "account.security": "Sécurité",
  "account.notifications": "Notifications",
  "account.password": "Mot de passe",
  "account.walletHint": "Cochez « Utiliser mon crédit wallet » sur la page de réservation.",
  // Favoris
  "fav.title": "Mes favoris",
  "fav.empty": "Vous n'avez pas encore de favoris.",
  "fav.priceAlerts": "Vos alertes de prix",
  "fav.countOne": "hébergement sauvegardé",
  "fav.countMany": "hébergements sauvegardés",
  "fav.emptyTitle": "Aucun favori",
  "fav.emptyDesc": "Sauvegardez vos hébergements préférés pour les retrouver facilement",
  "fav.alertsManaged": "Vos alertes prix sont gérées ci-dessus. Ajoutez-en depuis la fiche d'un hébergement (bouton « Suivre le prix »).",
  "fav.priceAlertsTitle": "Alertes prix",
  "fav.priceAlertsDesc": "Activez les alertes pour être notifié quand le prix d'un de vos favoris baisse.",
  // Messages
  "messages.empty": "Vos conversations avec les hébergeurs apparaîtront ici. Utilisez « Contacter l'hôte » sur une fiche ou depuis une réservation.",
  "messages.title": "Messages",
  "dash.overview": "Tableau de bord",
  "dash.properties": "Hébergements",
  "dash.rooms": "Chambres",
  "dash.bookings": "Réservations",
  "dash.reviews": "Avis",
  "dash.messages": "Messages",
  "dash.analytics": "Statistiques",
  "dash.billing": "Facturation",
  "dash.users": "Utilisateurs",
  "dash.promotions": "Promotions",
  "dash.audit": "Journal d'audit",
  "dash.settings": "Paramètres",
  "dash.help": "Aide",
  "dash.area": "Espace hébergeur",
  "dash.roleAdmin": "Administrateur",
  "dash.roleHost": "Hébergeur",
  "home.heroTitle1": "Réservez mieux.",
  "home.heroTitle2": "Voyagez plus.",
  "home.heroSub1": "Trouvez les meilleurs hébergements au meilleur prix.",
  "home.heroSub2": "Offres affichées, avis vérifiés et frais présentés avant confirmation.",
  "home.whereGo": "Où voulez-vous aller ?",
  "home.travelerOne": "voyageur",
  "home.travelerMany": "voyageurs",
  "home.search": "Rechercher",
  "home.trustPrice": "Prix vérifiés au paiement",
  "home.trustReviews": "Avis vérifiés",
  "home.trustNoFees": "0 frais cachés",
  "home.featuredTitle": "🔥 Hébergements populaires",
  "home.featuredSub": "Les mieux notés par nos voyageurs",
  "home.seeAll": "Voir tout",
  "home.seeAllProperties": "Voir tous les hébergements",
  "home.destTitle": "🌍 Destinations tendance",
  "home.discover": "Découvrir",
  "home.whyTitle": "✦ Pourquoi choisir MyBestBooking ?",
  "home.whyPriceTitle": "Prix vérifiés au paiement",
  "home.whyPriceBody": "Trouvé moins cher ailleurs ? On vous rembourse la différence. C'est notre engagement.",
  "home.whyReviewTitle": "Avis 100% Vérifiés",
  "home.whyReviewBody": "Seuls les voyageurs ayant réservé et séjourné peuvent laisser un avis. Zéro faux avis.",
  "home.whySupportTitle": "Support par email",
  "home.whySupportBody": "Une équipe humaine disponible à tout moment pour vous aider. Pas des bots.",
  "home.rewardsTitle": "Les vrais avantages, dès votre 1ère réservation",
  "home.rewardsBody": "Jusqu'à -20% sur les hébergements BestRewards et cashback Ambassador après séjour terminé.",
  "home.learnMore": "En savoir plus",
  "home.joinFree": "Rejoindre gratuitement",
  "home.firstVisit": "🚀 Première visite ?",
  "home.firstVisitBody": "Pour voir l'application en action avec des données de démonstration, cliquez sur le bouton ci-dessous.",
  "home.loadDemo": "Charger les données de démo",
  "notfound.title": "Page introuvable",
  "notfound.body": "Cette page n'existe pas ou plus. Peut-être avez-vous suivi un lien devenu obsolète ?",
  "notfound.home": "Retour à l'accueil",
} as const;

export type UiStringKey = keyof typeof FR;

const EN: Record<UiStringKey, string> = {
  "price.from": "From",
  "price.perNight": "/night",
  "price.unavailable": "Price unavailable",
  "price.fromShort": "From",
  "price.perNightLong": "per night",
  "price.convertedNote": "Indicative conversion · charged in",
  "book.seeAvailability": "See availability",
  "book.noRoom": "No room available",
  "book.reserve": "Book",
  "review.helpful": "Helpful",
  "review.thanks": "Thanks",
  "review.helpfulLogin": "— sign in required",
  "priceAlert.followBase": "Follow base price",
  "priceAlert.followStay": "Follow price for this stay",
  "headerActions.favoriteAdd": "Add to favorites",
  "headerActions.favoriteRemove": "Remove from favorites",
  "headerActions.favoriteAdded": "Added to your favorites",
  "headerActions.favoriteRemoved": "Removed from your favorites",
  "headerActions.share": "Share",
  "headerActions.shareLabel": "Share this property",
  "headerActions.linkCopied": "Link copied",
  "wishlist.copy": "Copied!",
  "wishlist.share": "Share",
  "priceAlert.title": "Price alerts",
  "priceAlert.empty": "You don't have any price alert yet. Click “Follow price” on a property page.",
  "priceAlert.belowPrefix": "Alert when price drops below",
  "priceAlert.confirmRemove": "Delete this alert?",
  "priceAlert.removeLabel": "Delete alert",
  "priceAlert.loading": "Loading…",
  "privacy.meta.title": "Privacy policy",
  "privacy.meta.description": "MyBestBooking personal data and cookies policy (GDPR).",
  "legal.meta.title": "Legal notice",
  "legal.meta.description": "Legal notice, terms of use and terms of sale of MyBestBooking.",
  "bestrewards.meta.title": "BestRewards — loyalty program",
  "bestrewards.meta.description": "Complete stays and unlock BestRewards discounts and Ambassador cashback.",
  "reservation.meta.title": "Complete my booking",
  "reservation.meta.description": "Review your selection and identity, then pay securely.",
  "bestrewards.hero": "Real rewards, from your 1st booking.<br/>Join the MyBestBooking loyalty program.",
  "bestrewards.join": "Join for free",
  "bestrewards.yourLevel": "Your level:",
  "bestrewards.yourLevelBadge": "Your level",
  "bestrewards.how": "How does it work?",
  "bestrewards.how1Title": "Sign up",
  "bestrewards.how1Desc": "It's free and instant. You immediately become Level 1 Explorer.",
  "bestrewards.how2Title": "Book",
  "bestrewards.how2Desc": "Every confirmed booking counts. The more you travel, the higher your level.",
  "bestrewards.how3Title": "Enjoy",
  "bestrewards.how3Desc": "Use your BestRewards discounts and, at Ambassador level, your wallet cashback.",
  "bestrewards.levelsTitle": "The 3 BestRewards levels",
  "bestrewards.faqTitle": "Frequently asked questions",
  "bestrewards.faq1Q": "How do I join BestRewards?",
  "bestrewards.faq1A": "It's automatic! As soon as you sign up on MyBestBooking, you are Level 1 Explorer and immediately benefit from the configured discount on BestRewards properties.",
  "bestrewards.faq2Q": "How do I level up?",
  "bestrewards.faq2A": "Every completed stay counts. After {n2} stays you reach Level 2 Traveller. After {n3} stays you reach Level 3 Ambassador.",
  "bestrewards.faq3Q": "Can discounts be combined?",
  "bestrewards.faq3A": "BestRewards discounts apply automatically to eligible properties (💎 badge). They can be combined with some promotions depending on partners.",
  "bestrewards.faq4Q": "How does Ambassador cashback work?",
  "bestrewards.faq4A": "At Level 3, you earn 5% cashback on every booking, credited straight to your MyBestBooking wallet. This balance can be used on your next bookings.",
  "bestrewards.faq5Q": "Can my level expire?",
  "bestrewards.faq5A": "Your level increases after each completed stay. Validity rules are not offered yet; your level does not expire automatically.",
  "bestrewards.ctaTitle": "Ready to enjoy the rewards?",
  "bestrewards.ctaDesc": "Join thousands of travellers saving with BestRewards",
  "bestrewards.ctaButton": "Create my free account",
  "bestrewards.level1Name": "Explorer",
  "bestrewards.level2Name": "Traveller",
  "bestrewards.level3Name": "Ambassador",
  "bestrewards.requirement1": "From sign-up",
  "bestrewards.requirementN": "{n} completed stays",
  "bestrewards.benefit1": "{pct}% discount on BestRewards properties",
  "bestrewards.benefit2": "Track your level in My account",
  "bestrewards.benefit2Level2": "All Explorer benefits",
  "bestrewards.benefitN": "{pct}% discount at {level} level on BestRewards",
  "bestrewards.benefitCashback": "5% cashback in wallet after your stay",
  "bestrewards.benefit2Level3": "All Traveller benefits",
  "share.label": "Shared list",
  "share.countOne": "{count} accommodation",
  "share.countMany": "{count} accommodations",
  "share.empty": "This list is empty for now.",
  "share.meta.title": "{name} — Shared list",
  "share.meta.description": "A shared list of accommodations on MyBestBooking.",
  "reservation.missingInfo": "Missing booking details",
  "reservation.yourSelection": "✦ Your selection",
  "reservation.arrivalTime": "Estimated arrival time",
  "reservation.unspecified": "Not specified",
  "reservation.securePaymentTitle": "Secure online payment",
  "reservation.securePaymentBody": "Card details are entered directly in the payment provider interface; MyBestBooking never stores them.",
  "reservation.confirmAfterPayment": "Your booking is only confirmed after the payment is actually validated.",
  "reservation.demoMode": "Demo mode: no real charge has been made.",
  "reservation.resumePayment": "Resume the same payment",
  "reservation.activateAccess": "Activate your access from the email sent, then sign in again to resume this payment without creating a new booking.",
  "reservation.viewBookings": "View my bookings",
  "reservation.backHome": "Back to home",
  "reservation.createAccount": "Create an account instead",
  "reservation.priceConfirmed": "Price confirmed before payment",
  "reservation.securePayment": "Secure payment",
  "reservation.loading": "Loading…",
  "reservation.adults": "Adults",
  "reservation.children": "Children",
  "reservation.ratePlan": "Rate and benefits",
  "reservation.standardRate": "Standard rate",
  "reservation.breakfastIncluded": " · breakfast included",
  "reservation.adultsOption": "{n} adult",
  "reservation.adultsOptionPlural": "{n} adults",
  "reservation.childrenOption": "{n} child",
  "reservation.childrenOptionPlural": "{n} children",
  "reservation.walletReductionNote": "Applied as a discount on the total, capped at the remaining amount. The wallet balance is in euros.",
  "reservation.walletLabel": "Wallet",
  "reservation.totalLabel": "Total",
  "reservation.bookingError": "Booking error",
  "reservation.paymentPendingRetry": "The payment is still being processed. Please try again in a few moments.",
  "reservation.checkInDate": "Check-in date",
  "reservation.checkOutDate": "Check-out date",
  "reservation.policyPrefix": "Policy: {policy}",
  "reservation.breakfastIncludedCaps": " · Breakfast included",
  "reservation.firstName": "First name",
  "reservation.phone": "Phone",
  "reservation.residenceCountry": "Country of residence",
  "reservation.unitedStates": "United States",
  "reservation.specialRequests": "Special requests (optional)",
  "reservation.specialRequestsPlaceholder": "E.g. quiet room, baby cot, late arrival...",
  "reservation.paymentConfirming": "Payment being confirmed",
  "reservation.confirmed": "🎉 It's confirmed!",
  "reservation.paymentTransmitted": "Your payment request has been sent. The booking will be confirmed once the payment provider responds securely.",
  "reservation.confirmationEmail": "📧 You will receive the final confirmation once the payment is completed.",
  "reservation.confirmationEmailSent": "A confirmation email will be sent to you.",
  "reservation.roomLabel": "Room",
  "reservation.promoCode": "Code {code}",
  "priceAlert.alertIf": "Alert me if",
  "priceAlert.totalNights": "the total nights of this stay (excl. taxes)",
  "priceAlert.basePrice": "the base price",
  "priceAlert.descendsUnder": "drops below:",
  "bookingCard.conversionTooltip": "Indicative conversion, fixed rates. Payment stays in the property's currency.",
  "meta.notFound": "Property not found",
  "meta.bookBestPrice": "Book at the best price.",
  "review.back": "Back to my bookings",
  "review.title": "Share your experience",
  "review.verifiedModerated": "Your stay is verified. Your review will be published after moderation.",
  "review.verifiedImmediate": "Your stay is already verified: your review will be published immediately after submission.",
  "review.overall": "Overall rating:",
  "review.subtitle": "Ratings by criterion",
  "review.subtitleHint": "(optional — equal to overall rating by default)",
  "review.ratingFor": "Rating for",
  "review.travelerType": "Travel type",
  "review.traveler.leisure": "Leisure",
  "review.traveler.solo": "Solo",
  "review.traveler.couple": "Couple",
  "review.traveler.family": "Family",
  "review.traveler.group": "Group",
  "review.traveler.business": "Business",
  "review.positiveLabel": "What you liked",
  "review.positivePlaceholder": "Tell us about your stay...",
  "review.negativeLabel": "What could be improved",
  "review.negativePlaceholder": "Optional",
  "review.publish": "Publish my review",
  "review.sendError": "Unable to submit your review",
  "review.genericError": "Submission error",
  "review.sentModerated": "Review submitted — awaiting moderation",
  "review.sentPublished": "Thank you, your review is published",
  "review.cleanliness": "Cleanliness",
  "review.comfort": "Comfort",
  "review.location": "Location",
  "review.facilities": "Facilities",
  "review.staff": "Welcome / service",
  "review.value": "Value for money",
  "crumb.home": "Home",
  "crumb.properties": "Properties",
  "badge.eco": "🌱 Eco",
  "trust.title": "MyBestBooking information",
  "trust.priceChecked": "Price verified at payment",
  "trust.feesShown": "Fees shown before confirmation",
  "trust.supportEmail": "Contact support by email",
  "help.heroTitle": "How can we help you?",
  "help.heroSubtitle": "Search for an answer or contact our team by email.",
  "help.searchPlaceholder": "Search in the help center…",
  "help.articles": "Articles",
  "help.noResults": "No article matches your search.",
  "help.selectArticle": "Select an article.",
  "help.writeSupport": "Write to support",
  "help.mailSubject": "MyBestBooking help",
  "help.meta.title": "Help and FAQ",
  "help.meta.description": "Find concrete answers about bookings, payments, account and stays.",
  "book.checkIn": "Check-in",
  "book.checkOut": "Check-out",
  "book.adults": "Adults",
  "book.children": "Children",
  "book.cancelShown": "✓ Cancellation policy shown before confirmation",
  "book.cancel.free": "Free cancellation",
  "book.cancel.flexible": "Free cancellation up to 24 h before arrival, then 100%",
  "book.cancel.moderate": "Free cancellation up to 5 days before, then 50% (100% under 24 h)",
  "book.cancel.strict": "Free cancellation up to 30 days before, then 50% (100% under 7 days)",
  "book.cancel.nonRefundable": "Non-refundable",
  "fav.add": "Add to favorites",
  "fav.added": "Added to favorites",
  "fav.remove": "Remove from favorites",
  "card.reviews": "reviews",
  "card.viewRooms": "View rooms →",
  "contact.host": "Contact the host",
  "contact.question": "Ask the host a question before booking",
  "contact.error": "Could not start the conversation",
  "contact.notFound": "Conversation not found",
  "nav.login": "Log in",
  "nav.myAccount": "My account",
  "nav.bookings": "My bookings",
  "nav.favorites": "My favorites",
  "nav.messages": "Messages",
  "nav.dashboard": "Dashboard",
  "nav.logout": "Log out",
  "nav.search": "Search",
  "nav.bestrewards": "BestRewards",
  "nav.help": "Help",
  "nav.accommodations": "Accommodations",
  "nav.signup": "Sign up",
  "nav.userMenu": "User menu",
  "nav.openMenu": "Open menu",
  "nav.closeMenu": "Close menu",
  "nav.level": "Level",
  "nav.darkModeOn": "Switch to light mode",
  "nav.darkModeOff": "Switch to dark mode",
  "nav.unreadOne": "{n} unread message",
  "nav.unreadMany": "{n} unread messages",
  "nav.languageSaveError": "Could not save the preference",
  "nav.roleAdmin": "Administrator",
  "nav.roleHost": "Host",
  "footer.discover": "Discover",
  "footer.searchAccommodation": "Search accommodation",
  "footer.helpCenter": "Help center",
  "footer.travelers": "Travelers",
  "footer.messaging": "Messages",
  "footer.hosts": "Hosts",
  "footer.addProperty": "List my property",
  "footer.hostArea": "Host dashboard",
  "footer.createAccount": "Create an account",
  "footer.contact": "Contact",
  "footer.tagline": "Book better. Travel further.",
  "footer.legal": "Legal notice",
  "footer.privacy": "Privacy",
  "footer.rights": "© 2025 MyBestBooking — All rights reserved",
  "search.title": "Accommodation search",
  "search.destination": "Destination",
  "search.destinationPlaceholder": "City or accommodation",
  "search.arrival": "Check-in",
  "search.departure": "Check-out",
  "search.type": "Type",
  "search.allTypes": "All types",
  "search.type.hotel": "Hotel",
  "search.type.apartment": "Apartment",
  "search.type.villa": "Villa",
  "search.type.hostel": "Hostel",
  "search.type.guesthouse": "Guesthouse",
  "search.type.riad": "Riad",
  "search.type.resort": "Resort",
  "search.travelers": "Travelers",
  "search.travelersPlaceholder": "Guests",
  "search.amenity": "Amenity",
  "search.amenity.all": "All",
  "search.sort": "Sort",
  "search.sort.rating": "Top rated",
  "search.sort.priceAsc": "Price: low to high",
  "search.sort.priceDesc": "Price: high to low",
  "search.priceMin": "Min price",
  "search.priceMax": "Max price",
  "search.button": "Search",
  "search.resultsCount": "result",
  "search.resultsPlural": "results",
  "search.pageOf": "of",
  "search.pageShort": "page",
  "search.prev": "Previous",
  "search.next": "Next",
  "search.empty": "No accommodation matches your criteria.",
  "search.currencyHint": "Filtering in your display currency.",
  "amenity.pool": "Pool",
  "amenity.restaurant": "Restaurant",
  "search.accommodationsIn": "Accommodation in",
  "search.allAccommodations": "All accommodations",
  "search.noResults": "No results",
  "search.noneInCity": "No accommodation found in \"{city}\". Try another destination.",
  "search.startSearch": "Start your search to find accommodation.",
  "search.backHome": "Back to home",
  "search.pagination": "Results pagination",
  "search.walletBanner": "You have {amount} in BestRewards credits. Remember to tick \"Use my credits\" at checkout to deduct them from your stay.",
  "action.save": "Save",
  "action.saved": "Changes saved",
  "action.cancel": "Cancel",
  "action.confirm": "Confirm",
  "action.back": "Back",
  "action.loading": "Loading…",
  "action.close": "Close",
  "action.send": "Send",
  "auth.login": "Login",
  "auth.register": "Sign up",
  "auth.email": "Email address",
  "auth.password": "Password",
  "auth.firstName": "First name",
  "auth.lastName": "Last name",
  "auth.loginButton": "Log in",
  "auth.registerButton": "Create my account",
  "auth.logoutButton": "Log out",
  "auth.forgotPassword": "Forgot password?",
  "auth.noAccount": "No account yet?",
  "auth.hasAccount": "Already have an account?",
  "auth.signupLink": "Sign up",
  "auth.loginLink": "Log in",
  "property.about": "About",
  "property.amenities": "Amenities",
  "property.reviews": "Reviews",
  "property.rooms": "Available rooms",
  "property.noRooms": "No room available at the moment",
  "property.cancellationFree": "free cancellation",
  "property.cancellationNonRefundable": "non-refundable",
  "property.cancellationSeeRate": "see rate",
  "property.newPartner": "New partner — no reviews yet",
  "property.reviewPlural": "reviews",
  "property.hostReply": "Host reply",
  "property.verifiedReviews": "Verified reviews",
  "property.policies": "Policies",
  "reservation.title": "Complete your booking",
  "reservation.continuePayment": "Continue to payment",
  "reservation.totalPaid": "Total paid",
  "reservation.amountToConfirm": "Amount to confirm",
  "reservation.allInclusive": "all taxes included",
  "reservation.nights": "night",
  "reservation.nightsPlural": "nights",
  "reservation.subtotal": "Subtotal",
  "reservation.taxes": "Taxes",
  "reservation.useWallet": "Use my wallet credit",
  "reservation.guestTitle": "You are booking as a guest",
  "reservation.bookingConfirmed": "Booking confirmed",
  "reservation.refLabel": "Reference",
  "reservation.stepSelection": "Your selection",
  "reservation.stepInfo": "Your details",
  "reservation.stepPayment": "Payment",
  "reservation.stepDone": "Confirmed!",
  "reservation.yourInfo": "Your details",
  "reservation.bookedAs": "Booked under your account",
  "reservation.taxesFees": "Taxes and fees",
  "reservation.walletAvailable": "Use my wallet credit",
  "reservation.walletAvail": "available",
  "reservation.guestMode": "Guest mode",
  "reservation.guestModeDesc": "you are booking without creating an account.",
  // T-152 (audit n°24) : reprise de paiement depuis /mes-reservations
  "reservation.resumeError": "Unable to load the booking",
  "reservation.cannotResume": "This booking is no longer awaiting payment.",
  "reservation.alreadyConfirmed": "This booking is already confirmed.",
  "reservation.payPending": "Payment pending",
  "reservation.seeBookings": "View my bookings",
  "bookings.title": "My bookings",
  "bookings.empty": "You don't have any bookings yet.",
  "bookings.upcoming": "Upcoming",
  "bookings.past": "Completed",
  "bookings.total": "Total",
  "bookings.viewProperty": "View property",
  "bookings.leaveReview": "Leave a review",
  "bookings.fee": "Fee",
  "bookings.refund": "Refund",
  "bookings.refundDone": "done",
  "bookings.refundPending": "pending",
  "bookings.refundNone": "not required",
  "status.pending": "Pending",
  "status.confirmed": "Confirmed",
  "status.cancelled": "Cancelled",
  "status.completed": "Completed",
  "status.no_show": "No-show",
  "common.noBooking": "No bookings",
  "bookings.subtitle": "Find all your MyBestBooking bookings",
  "bookings.emptyDesc": "You haven't made any booking yet. Find your next stay!",
  "bookings.explore": "Explore accommodations",
  // T-152 (audit n°24) : actions pending + état avis
  "bookings.payNow": "Pay now",
  "bookings.payPending": "Payment pending",
  "bookings.reviewPublished": "Review published",
  "bookings.reviewPending": "Pending moderation",
  "bookings.reviewSubmitted": "Review submitted",
  "bookings.alreadyReviewed": "You have already published a review for this booking.",
  "bookings.reviewSoon": "Review coming soon — reviews open after your stay.",
  "bookings.yourRating": "Your rating",
  "bookings.reviewBack": "Back to my bookings",
  "bookings.viewAccommodation": "View accommodation",
  "account.personalInfo": "Personal information",
  "account.phone": "Phone",
  "account.country": "Country (ISO-2)",
  "account.language": "Language",
  "account.currency": "Currency",
  "account.timezone": "Time zone",
  "account.avatar": "Profile photo (URL)",
  "account.avatarHint": "Leave empty to show your initials. Public image URL.",
  "account.wallet": "Wallet credit",
  "account.security": "Security",
  "account.notifications": "Notifications",
  "account.password": "Password",
  "account.walletHint": "Tick “Use my wallet credit” on the booking page.",
  "fav.title": "My favorites",
  "fav.empty": "You don't have any favorites yet.",
  "fav.priceAlerts": "Your price alerts",
  "fav.countOne": "saved accommodation",
  "fav.countMany": "saved accommodations",
  "fav.emptyTitle": "No favorites",
  "fav.emptyDesc": "Save your favorite accommodations to find them easily",
  "fav.alertsManaged": "Your price alerts are managed above. Add one from an accommodation page (“Track price” button).",
  "fav.priceAlertsTitle": "Price alerts",
  "fav.priceAlertsDesc": "Enable alerts to be notified when the price of a favorite drops.",
  "messages.empty": "Your conversations with hosts will appear here. Use “Contact the host” on a listing or from a booking.",
  "messages.title": "Messages",
  "dash.overview": "Dashboard",
  "dash.properties": "Properties",
  "dash.rooms": "Rooms",
  "dash.bookings": "Bookings",
  "dash.reviews": "Reviews",
  "dash.messages": "Messages",
  "dash.analytics": "Analytics",
  "dash.billing": "Billing",
  "dash.users": "Users",
  "dash.promotions": "Promotions",
  "dash.audit": "Audit log",
  "dash.settings": "Settings",
  "dash.help": "Help",
  "dash.area": "Host area",
  "dash.roleAdmin": "Administrator",
  "dash.roleHost": "Host",
  "home.heroTitle1": "Book better.",
  "home.heroTitle2": "Travel further.",
  "home.heroSub1": "Find the best stays at the best price.",
  "home.heroSub2": "Clear offers, verified reviews and fees shown before you confirm.",
  "home.whereGo": "Where do you want to go?",
  "home.travelerOne": "traveler",
  "home.travelerMany": "travelers",
  "home.search": "Search",
  "home.trustPrice": "Prices verified at checkout",
  "home.trustReviews": "Verified reviews",
  "home.trustNoFees": "No hidden fees",
  "home.featuredTitle": "🔥 Popular accommodations",
  "home.featuredSub": "Top rated by our travelers",
  "home.seeAll": "See all",
  "home.seeAllProperties": "See all accommodations",
  "home.destTitle": "🌍 Trending destinations",
  "home.discover": "Discover",
  "home.whyTitle": "✦ Why choose MyBestBooking?",
  "home.whyPriceTitle": "Prices verified at checkout",
  "home.whyPriceBody": "Found it cheaper elsewhere? We refund the difference. That's our promise.",
  "home.whyReviewTitle": "Avis 100% Vérifiés",
  "home.whyReviewBody": "Only travelers who booked and stayed can leave a review. Zero fake reviews.",
  "home.whySupportTitle": "Email support",
  "home.whySupportBody": "A real team available anytime to help you. No bots.",
  "home.rewardsTitle": "Real benefits from your very first booking",
  "home.rewardsBody": "Up to -20% on BestRewards stays and Ambassador cashback after your completed trip.",
  "home.learnMore": "Learn more",
  "home.joinFree": "Join for free",
  "home.firstVisit": "🚀 First visit?",
  "home.firstVisitBody": "To see the app in action with demo data, click the button below.",
  "home.loadDemo": "Load demo data",
  "notfound.title": "Page not found",
  "notfound.body": "This page does not exist anymore. Maybe you followed an outdated link?",
  "notfound.home": "Back to home",
};

export function isUiLocale(locale: string | null | undefined): locale is UiLocale {
  return locale === "fr" || locale === "en";
}

export function uiStrings(locale: string | null | undefined): Record<UiStringKey, string> {
  const loc = isUiLocale(locale) ? locale : "fr";
  return loc === "en" ? EN : FR;
}

/** Accès pratique : renvoie une fonction `t(key)` pour une langue donnée. */
export function makeT(locale: string | null | undefined): (key: UiStringKey) => string {
  const dict = uiStrings(locale);
  return (key: UiStringKey) => dict[key];
}
